# Generated by Django 4.2.1 on 2023-08-18 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.functions.fileValidation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=255, verbose_name='Venue Name')),
                ('vdescriptions', models.TextField(verbose_name='Venue Descripton')),
                ('vtype', models.CharField(max_length=50, verbose_name='Venue Type')),
                ('vaddress', models.CharField(max_length=255, verbose_name='Venue Address')),
                ('vcharges', models.CharField(max_length=15, verbose_name='Venue Charges')),
                ('file', models.FileField(upload_to='uploads/', validators=[myapp.functions.fileValidation.validate_file_extension], verbose_name='Venue Image')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Event Descriptions')),
                ('bookdate', models.DateTimeField(auto_now_add=True, verbose_name='Book Date')),
                ('eventdate', models.DateField(verbose_name='Event Date')),
                ('charges', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_by', to=settings.AUTH_USER_MODEL, verbose_name='Book By')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='myapp.venue', verbose_name='Venue Name')),
            ],
        ),
    ]
