# Generated by Django 4.2.1 on 2023-08-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='eventdate',
        ),
        migrations.AddField(
            model_name='book',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='book',
            name='from_date',
            field=models.DateField(null=True, verbose_name='booking date'),
        ),
    ]
